// static data - no db import
import {
  categories,
  products,
  storeSettings,
  type NewCategory,
  type NewProduct,
  type NewStoreSettings,
} from "@/db/schema";


const USD_TO_LYD = 5.5;

function toLyd(amount: number): number {
  return Math.round(amount * USD_TO_LYD * 100) / 100;
}

function toLydOrNull(amount: number | null | undefined): number | null {
  if (amount === null || amount === undefined) return null;
  return toLyd(amount);
}

export const INITIAL_CATEGORIES: NewCategory[] = [
  {
    slug: "notebooks",
    nameEn: "Notebooks & Paper Goods",
    nameAr: "الدفاتر والمنتجات الورقية",
    descriptionEn: "100gsm fountain-pen friendly notebooks, dotted journals, academic pads & archival A4 paper.",
    descriptionAr: "دفاتر ملاحظات فاخرة بوزن 100 جرام، دفاتر منقطة، كراسات أكاديمية وورق A4 عالي الجودة.",
    imageUrl: "https://images.pexels.com/photos/8251117/pexels-photo-8251117.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    badgeEn: "100–120 GSM Paper",
    badgeAr: "ورق فاخر 120 جرام",
    sortOrder: 1,
  },
  {
    slug: "writing",
    nameEn: "Fine Writing & Pens",
    nameAr: "أدوات الكتابة والأقلام الفاخرة",
    descriptionEn: "Precision fountain pens, Japanese gel rollers, architectural fineliners & pastel highlighters.",
    descriptionAr: "أقلام حبر سائلة دقيقة، أقلام جل يابانية، محددات هندسية وأقلام تظليل بألوان الباستيل.",
    imageUrl: "/images/cat-pens.jpg",
    badgeEn: "Precision Nib",
    badgeAr: "كتابة فائقة الدقة",
    sortOrder: 2,
  },
  {
    slug: "bags",
    nameEn: "School Bags & Organizers",
    nameAr: "الحقائب المدرسية وحلول التنظيم",
    descriptionEn: "Ergonomic waterproof backpacks, padded laptop sleeves, canvas pen cases & modular desk trays.",
    descriptionAr: "حقائب ظهر مدرسية مريحة ومقاومة للماء، حافظات حاسوب مبطنة، مقلمات قماشية ومنظمات مكتبية.",
    imageUrl: "/images/cat-bags.jpg",
    badgeEn: "Ergonomic Series",
    badgeAr: "تصميم مريح للظهر",
    sortOrder: 3,
  },
  {
    slug: "it-peripherals",
    nameEn: "IT Peripherals & Accessories",
    nameAr: "ملحقات الحاسوب والتقنية",
    descriptionEn: "Wireless mechanical keyboards, ergonomic silent mice, USB-C 10-in-1 hubs & NVMe portable SSDs.",
    descriptionAr: "لوحات مفاتيح ميكانيكية لاسلكية، فئران مريحة صامتة، موزعات USB-C وأقراص تخزين SSD سريعة.",
    imageUrl: "https://images.pexels.com/photos/12512639/pexels-photo-12512639.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    badgeEn: "Pro Studio Tech",
    badgeAr: "تقنيات احترافية",
    sortOrder: 4,
  },
  {
    slug: "ink-consumables",
    nameEn: "Ink, Toner & Consumables",
    nameAr: "الأحبار والتونر والمستهلكات",
    descriptionEn: "High-yield laser toner cartridges, pigment ink bottles, thermal labels & studio paper reams.",
    descriptionAr: "خراطيش تونر ليزر عالية الإنتاجية، عبوات حبر ملونة، ملصقات حرارية ورزم ورق للمكاتب.",
    imageUrl: "/images/cat-ink-toner.jpg",
    badgeEn: "High-Yield OEM",
    badgeAr: "إنتاجية طباعة عالية",
    sortOrder: 5,
  },
  {
    slug: "art-drafting",
    nameEn: "Art & Technical Drafting",
    nameAr: "الفنون الجميلة والرسم الهندسي",
    descriptionEn: "Dual-tip alcohol markers, brass drafting compass sets, watercolor brush pens & heavy sketchbooks.",
    descriptionAr: "أقلام ماركر مزدوجة الرأس، أطقم فرجار هندسي نحاسي، أقلام ألوان مائية وكراسات رسم سميكة.",
    imageUrl: "/images/cat-art-drafting.jpg",
    badgeEn: "Studio Grade",
    badgeAr: "درجة استوديو فنية",
    sortOrder: 6,
  },
  {
    slug: "calculators-tech",
    nameEn: "Calculators & Desk Tech",
    nameAr: "الآلات الحاسبة وإلكترونيات المكتب",
    descriptionEn: "Scientific graphing calculators, solar financial calculators, LED desk lamps & Pomodoro timers.",
    descriptionAr: "آلات حاسبة علمية وبيانية، حاسبات مكتبية بالطاقة الشمسية، مصابيح LED ذكية ومؤقتات الدراسة.",
    imageUrl: "/images/cat-calculators.jpg",
    badgeEn: "Exam Approved",
    badgeAr: "معتمدة للامتحانات",
    sortOrder: 7,
  },
];

export const INITIAL_PRODUCTS: NewProduct[] = [
  // 1. Notebooks
  {
    sku: "NB-ATELIER-01",
    categorySlug: "notebooks",
    titleEn: "Kyoto Linen Hardcover Dotted Journal A5 (Set of 2)",
    titleAr: "دفتر كيوتو بغلافتان من الكتان منقط حجم A5 (طقم من قطعتين)",
    descriptionEn: "Thread-bound lay-flat A5 journals featuring 120gsm ivory Japanese acid-free paper. Zero bleed-through with fountain pens and markers, complete with dual ribbon bookmarks and expandable inner pocket.",
    descriptionAr: "دفتر ملاحظات A5 يفتح بشكل مسطح بالكامل مع ورق ياباني عاجي بوزن 120 جرام خالٍ من الأحماض. مثالي لأقلام الحبر السائل دون تسرب، مزود بشريطين مرجعيين وجيب داخلي.",
    price: 24.90,
    originalPrice: 32.00,
    wholesalePrice: 17.50,
    wholesaleMinQty: 15,
    stock: 140,
    images: [
      "https://images.pexels.com/photos/8251117/pexels-photo-8251117.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/1174122/pexels-photo-1174122.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    specsEn: "A5 (148 × 210 mm) • 192 Pages • 120 GSM Ivory Paper",
    specsAr: "حجم A5 • 192 صفحة • ورق عاجي 120 جرام",
  },
  {
    sku: "NB-SPIRAL-02",
    categorySlug: "notebooks",
    titleEn: "Academic Pro B5 Twin-Wire Grid Notebook Pack (5 pcs)",
    titleAr: "مجموعة دفاتر أكاديمية B5 بسلك مزدوج مربعات (5 قطع)",
    descriptionEn: "Engineered for university lectures and STEM notes. Micro-perforated 100gsm sheets with smart margin rules and color-coded polypropylene waterproof covers.",
    descriptionAr: "مصممة للمحاضرات الجامعية والملاحظات العلمية. أوراق بوزن 100 جرام قابلة للنزع الدقيق مع أغلفة مقاومة للماء بألوان متعددة.",
    price: 19.50,
    originalPrice: 24.00,
    wholesalePrice: 13.80,
    wholesaleMinQty: 20,
    stock: 280,
    images: [
      "https://images.pexels.com/photos/7657377/pexels-photo-7657377.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/867483/pexels-photo-867483.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    specsEn: "B5 • 5 Notebooks × 120 Sheets • 100 GSM",
    specsAr: "حجم B5 • 5 دفاتر × 120 ورقة • 100 جرام",
  },
  {
    sku: "NB-PLANNER-03",
    categorySlug: "notebooks",
    titleEn: "Architect Weekly Desk Planner & Sticky Note Folio",
    titleAr: "منظم المكتب الأسبوعي وحافظة الملاحظات اللاصقة",
    descriptionEn: "Undated 52-week panoramic desk pad paired with 6 sizes of pastel architectural index tabs and grid sticky notes.",
    descriptionAr: "منظم مكتبي أسبوعي يكفي لمدة 52 أسبوعاً غير مؤرخ، مرفق مع 6 أحجام من الملاحظات اللاصقة وفواصل التصنيف.",
    price: 16.00,
    originalPrice: null,
    wholesalePrice: 11.20,
    wholesaleMinQty: 25,
    stock: 95,
    images: [
      "https://images.pexels.com/photos/1007025/pexels-photo-1007025.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/5594313/pexels-photo-5594313.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    specsEn: "52 Tear-Off Sheets • 450 Sticky Notes Included",
    specsAr: "52 ورقة أسبوعية • 450 ملاحظة لاصقة مرفقة",
  },

  // 2. Fine Writing & Pens
  {
    sku: "WR-FOUNT-01",
    categorySlug: "writing",
    titleEn: "Meister Matte Black & Brass Fountain Pen (Fine Nib)",
    titleAr: "قلم حبر سائل مايستر أسود مطفي ونحاسي (ريشة دقيقة)",
    descriptionEn: "Balanced anodized aluminum barrel with a German iridium-tipped fine nib. Includes refillable piston converter and 2 archival midnight-blue ink cartridges.",
    descriptionAr: "هيكل متوازن من الألمنيوم المؤكسد مع ريشة ألمانية دقيقة مطلية بالإيريديوم. يشمل محول تعبئة وعبوتين من الحبر الأزرق الليلي.",
    price: 38.00,
    originalPrice: 48.00,
    wholesalePrice: 26.50,
    wholesaleMinQty: 10,
    stock: 85,
    images: [
      "/images/cat-pens.jpg",
      "/images/hero-stationery.jpg",
    ],
    isFeatured: true,
    isPromotion: true,
    specsEn: "0.5mm Fine German Nib • Converter Included",
    specsAr: "ريشة ألمانية 0.5 ملم • مرفق مع محول تعبئة",
  },
  {
    sku: "WR-GEL-02",
    categorySlug: "writing",
    titleEn: "Sakura Smooth-Flow 0.5mm Gel Roller Set (12 Colors)",
    titleAr: "طقم أقلام جل ساكورا سريعة الجفاف 0.5 ملم (12 لوناً)",
    descriptionEn: "Instant-dry pigment gel ink prevents smudging for both left-handed and right-handed writers. Ergonomic silicone grip for marathon exam sessions.",
    descriptionAr: "حبر جل صبغي سريع الجفاف يمنع التلطخ لليد اليمنى واليسرى. قبضة سيليكون مريحة لجلسات الدراسة والامتحانات الطويلة.",
    price: 14.90,
    originalPrice: 18.50,
    wholesalePrice: 9.80,
    wholesaleMinQty: 24,
    stock: 320,
    images: [
      "https://images.pexels.com/photos/236135/pexels-photo-236135.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/10605238/pexels-photo-10605238.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    specsEn: "12 Pens • 0.5mm Twin-Ball Tip • Waterproof Ink",
    specsAr: "12 قلماً • رأس 0.5 ملم • حبر مقاوم للماء",
  },
  {
    sku: "WR-PASTEL-03",
    categorySlug: "writing",
    titleEn: "Nordic Dual-Tip Chisel & Fine Pastel Highlighters (8 Pack)",
    titleAr: "مجموعة أقلام تظليل باستيل مزدوجة الرأس (8 ألوان)",
    descriptionEn: "Soft muted tones that highlight key study passages without fatiguing the eyes. Features a 4mm chisel tip and a 1mm underlining tip.",
    descriptionAr: "ألوان باستيل هادئة تبرز النصوص المهمة دون إجهاد العين. مزودة برأس مشطوف 4 ملم ورأس دقيق 1 ملم للتسطير.",
    price: 11.50,
    originalPrice: null,
    wholesalePrice: 7.90,
    wholesaleMinQty: 30,
    stock: 210,
    images: [
      "https://images.pexels.com/photos/5594313/pexels-photo-5594313.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "/images/cat-pens.jpg",
    ],
    isFeatured: false,
    isPromotion: false,
    specsEn: "8 Muted Tones • Dual Tip (4mm + 1mm)",
    specsAr: "8 ألوان هادئة • رأس مزدوج (4 ملم + 1 ملم)",
  },

  // 3. School Bags & Organizers
  {
    sku: "BG-PACK-01",
    categorySlug: "bags",
    titleEn: "Oslo Ergonomic 26L Waterproof Scholar & Laptop Backpack",
    titleAr: "حقيبة ظهر أوسلو المريحة المقاومة للماء سعة 26 لتر مع جيب للحاسوب",
    descriptionEn: "Orthopedic breathable back support, dedicated 16-inch suspended laptop compartment, hidden anti-theft pocket, and water-repellent ballistic nylon.",
    descriptionAr: "دعم طبي مريح للظهر قابل للتهوية، قسم مبطن مخصص لحاسوب محمول حتى 16 بوصة، جيب خفي مضاد للسرقة وقماش مقاوم للماء.",
    price: 59.00,
    originalPrice: 75.00,
    wholesalePrice: 41.00,
    wholesaleMinQty: 10,
    stock: 65,
    images: [
      "/images/cat-bags.jpg",
      "/images/hero-backtoschool.jpg",
    ],
    isFeatured: true,
    isPromotion: true,
    specsEn: "26L Capacity • Fits 16\" Laptop • Water-Repellent",
    specsAr: "سعة 26 لتر • تناسب حاسوب 16 بوصة • مقاومة للماء",
  },
  {
    sku: "BG-CASE-02",
    categorySlug: "bags",
    titleEn: "Expandable Cordura Standing Pencil & Tech Pouch",
    titleAr: "مقلمة وحافظة تقنية قابلة للتوسيع من قماش كوردورا المتين",
    descriptionEn: "Holds up to 45 pens, a scientific calculator, USB cables, and power bank. Folds down into a magnetic standing desk caddy in seconds.",
    descriptionAr: "تتسع لـ 45 قلماً، آلة حاسبة علمية، كابلات USB وشاحن متنقل. تتحول إلى حامل مكتبي قائم بفضل المغناطيس المدمج.",
    price: 18.00,
    originalPrice: 22.00,
    wholesalePrice: 12.50,
    wholesaleMinQty: 20,
    stock: 150,
    images: [
      "/images/cat-bags.jpg",
      "https://images.pexels.com/photos/14541073/pexels-photo-14541073.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: true,
    specsEn: "Cordura 1000D • Magnetic Stand • 6 Mesh Pockets",
    specsAr: "قماش كوردورا متين • قاعدة مغناطيسية • 6 جيوب داخلية",
  },
  {
    sku: "BG-TRAY-03",
    categorySlug: "bags",
    titleEn: "Modular Walnut & Matte Steel Desktop Organizer Suite",
    titleAr: "طقم تنظيم المكتب المعياري من خشب الجوز والفولاذ المطفي",
    descriptionEn: "4-piece interlocking desk tray system for documents, pens, smartphones, and sticky notes with non-slip cork base.",
    descriptionAr: "نظام تنظيم مكتبي مكون من 4 قطع متداخلة للمستندات والأقلام والهواتف الذكية مع قاعدة من الفلين المانع للانزلاق.",
    price: 34.00,
    originalPrice: null,
    wholesalePrice: 24.00,
    wholesaleMinQty: 12,
    stock: 50,
    images: [
      "/images/landscape-banner.jpg",
      "/images/cat-bags.jpg",
    ],
    isFeatured: false,
    isPromotion: false,
    specsEn: "4 Modular Pieces • Solid Walnut & Powder-Coated Steel",
    specsAr: "4 قطع معيارية • خشب جوز طبيعي وفولاذ مطلي",
  },

  // 4. IT Peripherals & Accessories
  {
    sku: "IT-KEY-01",
    categorySlug: "it-peripherals",
    titleEn: "KeyChronos Low-Profile Wireless Mechanical Keyboard (Tri-Mode)",
    titleAr: "لوحة مفاتيح ميكانيكية لاسلكية نحيفة كي-كرونوس (ثلاثية الاتصال)",
    descriptionEn: "Connect up to 3 devices via Bluetooth 5.2, 2.4GHz dongle, or USB-C. Hot-swappable tactile quiet switches with warm white backlight and Mac/Windows/Arabic keycap support.",
    descriptionAr: "اتصال بثلاثة أجهزة عبر البلوتوث 5.2 أو مستقبل 2.4 جيجاهرتز أو كابل USB-C. مفاتيح ميكانيكية هادئة مع إضاءة خلفية مريحة ودعم كامل لنظامي ماك وويندوز.",
    price: 89.00,
    originalPrice: 109.00,
    wholesalePrice: 64.00,
    wholesaleMinQty: 8,
    stock: 48,
    images: [
      "https://images.pexels.com/photos/38094551/pexels-photo-38094551.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/12512639/pexels-photo-12512639.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    specsEn: "75% Layout • Bluetooth 5.2 + 2.4GHz • 180h Battery",
    specsAr: "حجم 75% مدمج • بلوتوث 5.2 + لاسلكي • بطارية 180 ساعة",
  },
  {
    sku: "IT-MOUSE-02",
    categorySlug: "it-peripherals",
    titleEn: "ErgoFlow Master Silent Wireless Mouse (8000 DPI Sensor)",
    titleAr: "فأرة لاسلكية احترافية صامتة إيرغو-فلو (حساس 8000 DPI)",
    descriptionEn: "Sculpted thumb rest with electromagnetic MagSpeed scroll wheel and 95% quieter clicks. Tracks on glass and wood surfaces with USB-C quick charge.",
    descriptionAr: "تصميم مريح لليد مع عجلة تمرير كهرومغناطيسية فائقة السرعة ونقرات صامتة بنسبة 95%. تعمل على كافة الأسطح بما فيها الزجاج مع شحن سريع USB-C.",
    price: 49.00,
    originalPrice: 62.00,
    wholesalePrice: 35.00,
    wholesaleMinQty: 10,
    stock: 75,
    images: [
      "https://images.pexels.com/photos/7151696/pexels-photo-7151696.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/9128856/pexels-photo-9128856.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    specsEn: "8000 DPI Glass Sensor • Silent Click • 70-Day Battery",
    specsAr: "حساس 8000 نقطة • نقرات صامتة • بطارية تدوم 70 يوماً",
  },
  {
    sku: "IT-HUB-03",
    categorySlug: "it-peripherals",
    titleEn: "HyperDock 10-in-1 Aluminum USB-C Hub & 1TB NVMe Enclosure",
    titleAr: "موزع USB-C احترافي 10 في 1 من الألمنيوم مع منفذ HDMI 4K",
    descriptionEn: "Features 4K@60Hz HDMI, Gigabit Ethernet, 100W PD pass-through charging, SD/TF card readers, and 4 high-speed USB 3.2 ports.",
    descriptionAr: "يضم منفذ HDMI بدقة 4K@60Hz، منفذ شبكة جيجابت، شحن سريع بقوة 100 واط، قارئ بطاقات ذاكرة و4 منافذ USB 3.2 فائقة السرعة.",
    price: 44.00,
    originalPrice: null,
    wholesalePrice: 31.00,
    wholesaleMinQty: 10,
    stock: 90,
    images: [
      "/images/hero-it-tech.jpg",
      "https://images.pexels.com/photos/28228014/pexels-photo-28228014.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    specsEn: "4K 60Hz HDMI • 100W PD • 10Gbps USB 3.2",
    specsAr: "دعم 4K 60Hz • شحن 100 واط • سرعة نقل 10 جيجابت",
  },

  // 5. Ink, Toner & Consumables
  {
    sku: "INK-TONER-01",
    categorySlug: "ink-consumables",
    titleEn: "LaserJet Pro High-Yield Black Toner Cartridge (3,500 Pages)",
    titleAr: "خرطوشة تونر ليزر أسود عالية الإنتاجية (3500 صفحة)",
    descriptionEn: "Smart-chip equipped high-density monochrome laser toner producing razor-sharp text and technical diagrams without smudging.",
    descriptionAr: "خرطوشة تونر ليزر مزودة بشريحة ذكية لطباعة نصوص ومخططات هندسية فائقة الوضوح والكثافة دون تلطخ.",
    price: 42.00,
    originalPrice: 54.00,
    wholesalePrice: 29.50,
    wholesaleMinQty: 10,
    stock: 110,
    images: [
      "/images/cat-ink-toner.jpg",
      "/images/hero-it-tech.jpg",
    ],
    isFeatured: true,
    isPromotion: true,
    specsEn: "3,500 Pages ISO Yield • Smart Chip • Crisp Black",
    specsAr: "إنتاجية 3500 صفحة • شريحة ذكية مدمجة • أسود فاحم",
  },
  {
    sku: "INK-CMYK-02",
    categorySlug: "ink-consumables",
    titleEn: "EcoTank CMYK Pigment Refill Ink Multipack (4 × 100ml Bottles)",
    titleAr: "طقم عبوات حبر إيكو-تانك الأربعة CMYK (4 × 100 مل)",
    descriptionEn: "Spill-free auto-stop nozzles delivering up to 7,500 color pages and 6,000 black pages with fade-resistant archival ink.",
    descriptionAr: "فوهات ذكية مانعة للانسكاب توفر طباعة حتى 7500 صفحة ملونة و6000 صفحة سوداء بحبر مقاوم للبهتان.",
    price: 29.90,
    originalPrice: 36.00,
    wholesalePrice: 21.00,
    wholesaleMinQty: 15,
    stock: 160,
    images: [
      "/images/cat-ink-toner.jpg",
      "/images/landscape-banner.jpg",
    ],
    isFeatured: false,
    isPromotion: true,
    specsEn: "4 × 100ml (C/M/Y/K) • 7,500 Page Yield",
    specsAr: "4 عبوات × 100 مل • تكفي لطباعة 7500 صفحة",
  },
  {
    sku: "INK-PAPER-03",
    categorySlug: "ink-consumables",
    titleEn: "Atelier Ultra-White 90gsm A4 Laser & Inkjet Paper Box (5 Reams / 2500 Sheets)",
    titleAr: "صندوق ورق A4 فائق البياض 90 جرام للطباعة الليزرية والحبرية (5 رزم / 2500 ورقة)",
    descriptionEn: "High-opacity CIE 168 whiteness paper engineered for jam-free high-speed duplex printing in schools, copy centers, and corporate offices.",
    descriptionAr: "ورق فائق البياض والنعومة مصمم للطباعة المزدوجة عالية السرعة دون انحشار، مثالي للمدارس والمكاتب والشركات.",
    price: 32.50,
    originalPrice: null,
    wholesalePrice: 24.90,
    wholesaleMinQty: 10,
    stock: 400,
    images: [
      "/images/cat-ink-toner.jpg",
      "https://images.pexels.com/photos/8251117/pexels-photo-8251117.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    specsEn: "5 Reams × 500 Sheets • 90 GSM • CIE 168 Whiteness",
    specsAr: "5 رزم × 500 ورقة • 90 جرام • بياض ناصع CIE 168",
  },

  // 6. Art & Technical Drafting
  {
    sku: "ART-MARK-01",
    categorySlug: "art-drafting",
    titleEn: "StudioPro 48-Color Dual-Tip Alcohol Art Markers in Carrying Case",
    titleAr: "حقيبة أقلام ماركر فنية مزدوجة الرأس 48 لوناً",
    descriptionEn: "Blendable alcohol-based ink with Japanese brush and broad chisel nibs for architecture rendering, illustration, and industrial design.",
    descriptionAr: "حبر كحولي قابل للدمج الاحترافي مع رأس فرشاة مرن ورأس عريض للرسم المعماري والتصميم الصناعي والفنون.",
    price: 45.00,
    originalPrice: 58.00,
    wholesalePrice: 31.50,
    wholesaleMinQty: 10,
    stock: 70,
    images: [
      "/images/cat-art-drafting.jpg",
      "https://images.pexels.com/photos/10607184/pexels-photo-10607184.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: true,
    isPromotion: true,
    specsEn: "48 Colors + Blender • Brush & Chisel Nibs",
    specsAr: "48 لوناً + قلم دمج • رأس فرشاة ورأس مشطوف",
  },
  {
    sku: "ART-GEOM-02",
    categorySlug: "art-drafting",
    titleEn: "Precision Solid Brass & Steel Architecture Compass & Drafting Kit",
    titleAr: "طقم الهندسة والرسم التقني الاحترافي من النحاس والفولاذ",
    descriptionEn: "Micro-screw adjustment giant bow compass, extension beam, anodized aluminum scale ruler, and metal protractor in a shockproof tin case.",
    descriptionAr: "فرجار هندسي دقيق ببرغي ضبط ميكروي، مسطرة مقياس من الألمنيوم المؤكسد ومنقلة معدنية داخل حافظة معدنية مقاومة للصدمات.",
    price: 22.00,
    originalPrice: null,
    wholesalePrice: 15.40,
    wholesaleMinQty: 15,
    stock: 115,
    images: [
      "/images/cat-art-drafting.jpg",
      "/images/hero-stationery.jpg",
    ],
    isFeatured: false,
    isPromotion: false,
    specsEn: "9-Piece Metal Set • Micro-Adjust Wheel",
    specsAr: "طقم معدني من 9 قطع • عجلة ضبط دقيقة",
  },
  {
    sku: "ART-SKETCH-03",
    categorySlug: "art-drafting",
    titleEn: "A4 Cold-Press 300gsm Watercolor & Mixed Media Pad (30 Sheets)",
    titleAr: "كراسة رسم مائي وفنون مختلطة A4 بوزن 300 جرام (30 لوحة)",
    descriptionEn: "100% cotton-blend textured cold-press sheets glued on all 4 sides to prevent warping under heavy washes.",
    descriptionAr: "أوراق فنية بملمس بارد غنية بالقطن بوزن 300 جرام مثالية للألوان المائية والأكريليك والغواش دون تموج الورق.",
    price: 17.50,
    originalPrice: 21.00,
    wholesalePrice: 12.20,
    wholesaleMinQty: 20,
    stock: 90,
    images: [
      "https://images.pexels.com/photos/10607184/pexels-photo-10607184.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "/images/cat-art-drafting.jpg",
    ],
    isFeatured: false,
    isPromotion: true,
    specsEn: "A4 • 300 GSM Cold-Press • Acid-Free",
    specsAr: "حجم A4 • وزن 300 جرام • خالٍ من الأحماض",
  },

  // 7. Calculators & Desk Tech
  {
    sku: "CALC-SCI-01",
    categorySlug: "calculators-tech",
    titleEn: "GraphMaster FX-991EX High-Resolution Scientific Calculator (552 Functions)",
    titleAr: "آلة حاسبة علمية متطورة عالية الدقة (552 وظيفة حسابية)",
    descriptionEn: "Natural textbook display showing matrices, integrals, vectors, and spreadsheet calculations exactly as written in textbooks. Dual solar & battery powered.",
    descriptionAr: "شاشة عرض طبيعية تظهر المعادلات والمصفوفات والتكاملات تماماً كما في الكتب الدراسية. تعمل بالطاقة الشمسية والبطارية.",
    price: 27.50,
    originalPrice: 34.00,
    wholesalePrice: 19.80,
    wholesaleMinQty: 12,
    stock: 130,
    images: [
      "/images/cat-calculators.jpg",
      "/images/hero-backtoschool.jpg",
    ],
    isFeatured: true,
    isPromotion: true,
    specsEn: "552 Functions • Natural Textbook LCD • Solar + Battery",
    specsAr: "552 وظيفة علمية • شاشة عرض طبيعية • طاقة مزدوجة",
  },
  {
    sku: "CALC-DESK-02",
    categorySlug: "calculators-tech",
    titleEn: "Tactile Mechanical-Switch 12-Digit Executive Financial Calculator",
    titleAr: "آلة حاسبة مكتبية مالية 12 رقماً بمفاتيح ميكانيكية مريحة",
    descriptionEn: "Tilted large LCD readout with crisp mechanical key switches, tax/margin keys, and brushed aluminum faceplate for accounting desks.",
    descriptionAr: "شاشة LCD كبيرة مائلة مع مفاتيح ميكانيكية سريعة الاستجابة وأزرار حساب الضرائب والربح وواجهة من الألمنيوم المصقول.",
    price: 21.00,
    originalPrice: null,
    wholesalePrice: 14.50,
    wholesaleMinQty: 15,
    stock: 80,
    images: [
      "/images/cat-calculators.jpg",
      "https://images.pexels.com/photos/399160/pexels-photo-399160.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    isFeatured: false,
    isPromotion: false,
    specsEn: "12-Digit Display • Mechanical Keys • GT & Tax Functions",
    specsAr: "شاشة 12 رقماً • مفاتيح ميكانيكية • وظائف المحاسبة والضرائب",
  },
  {
    sku: "CALC-LAMP-03",
    categorySlug: "calculators-tech",
    titleEn: "Luminaire Eye-Care Architect LED Desk Lamp with Wireless Charger",
    titleAr: "مصباح مكتب LED لحماية العين مع قاعدة شحن لاسلكي للهاتف",
    descriptionEn: "Flicker-free CRI 95+ studio lighting with 5 color temperatures (2700K–6500K), Pomodoro 45-minute study timer, and 15W Qi wireless charging pad.",
    descriptionAr: "إضاءة خالية من الوميض بمعيار CRI 95+ مع 5 درجات حرارة لونية، مؤقت دراسة ذكي وقاعدة شحن لاسلكي سريع بقوة 15 واط.",
    price: 46.00,
    originalPrice: 59.00,
    wholesalePrice: 32.00,
    wholesaleMinQty: 10,
    stock: 60,
    images: [
      "/images/landscape-banner.jpg",
      "/images/cat-calculators.jpg",
    ],
    isFeatured: false,
    isPromotion: true,
    specsEn: "CRI >95 Eye-Care • 15W Qi Wireless Pad • Study Timer",
    specsAr: "حماية للعين CRI 95+ • شاحن لاسلكي 15 واط • مؤقت دراسة",
  },
];

export const INITIAL_STORE_SETTINGS: NewStoreSettings = {
  storeNameEn: "Al Manhaj Company for Stationery",
  storeNameAr: "شركة المنهج للقرطاسية",
  taglineEn:
    "Office Tools • Engineering Equipment • School Supplies • Cabinets • Printer Ink & Computer Equipment",
  taglineAr:
    "أدوات مكتبية • معدات هندسية • أدوات مدرسية • خزائن مختلفة • حبر طابعات",
  whatsappNumber: "218912145050",
  contactEmail: "info@almanhaj.ly",
  contactPhone: "+218 91-214-5050",
  addressEn: "Al Bivi, Tripoli, Libya",
  addressAr: "البيفي، طرابلس، ليبيا",
  workingHoursEn: "Sat – Thu: 09:00 – 21:00",
  workingHoursAr: "السبت – الخميس: 09:00 صباحاً – 09:00 مساءً",
  currencyEn: "LYD",
  currencyAr: "د.ل",
  wholesaleDiscountTier1Pct: 15,
  wholesaleDiscountTier2Pct: 22,
  wholesaleDiscountTier3Pct: 30,
  wholesaleConditionsEn:
    "Enjoy instant B2B & institutional pricing for schools, universities, copy centers, and companies across Libya. Orders of 10+ units per SKU unlock Wholesale Price automatically. Free delivery in Tripoli on orders over 1,900 LYD and dedicated pro-forma invoicing via WhatsApp +218 91-214-5050.",
  wholesaleConditionsAr:
    "استفد من أسعار الجملة الفورية للمدارس والجامعات ومراكز الطباعة والشركات في ليبيا. الطلبات ابتداءً من 10 قطع للصنف الواحد تفعّل سعر الجملة تلقائياً، مع توصيل مجاني داخل طرابلس للطلبيات فوق 1,900 د.ل وفوترة احترافية مباشرة عبر واتساب 0912145050.",
  defaultTheme: "royal",
  heroSlides: [
    {
      id: "slide-1",
      imageUrl: "/images/hero-stationery.jpg",
      badgeEn: "2026 Academic & Studio Collection",
      badgeAr: "مجموعة الموسم الدراسي والاستوديو 2026",
      titleEn: "Tactile Paper Goods & Precision Writing Tools",
      titleAr: "قرطاسية فاخرة وأدوات كتابة وهندسة عالية الدقة",
      subtitleEn:
        "From 120gsm Japanese dotted notebooks to German-nib fountain pens — crafted for students, architects, and creators.",
      subtitleAr:
        "من الدفاتر اليابانية الفاخرة بوزن 120 جرام إلى أقلام الحبر السائل والأدوات الهندسية المصممة للطلاب والمبدعين.",
      ctaEn: "Explore Stationery",
      ctaAr: "استكشف القرطاسية",
      targetCategory: "notebooks",
    },
    {
      id: "slide-2",
      imageUrl: "/images/hero-it-tech.jpg",
      badgeEn: "IT Peripherals & Office Consumables",
      badgeAr: "معدات المعلوماتية والأحبار والمستهلكات",
      titleEn: "High-Performance Workspace Tech & Original Toners",
      titleAr: "ملحقات الحاسوب الاحترافية وأحبار الطباعة عالية الإنتاجية",
      subtitleEn:
        "Equip your study desk or company office with wireless mechanical keyboards, ergonomic mice, and high-yield laser toners.",
      subtitleAr:
        "جهّز مكتبك أو مؤسستك بلوحات المفاتيح الميكانيكية اللاسلكية والفئران المريحة وخراطيش الليزر والأوراق الفاخرة.",
      ctaEn: "Shop IT & Consumables",
      ctaAr: "تسوّق التقنية والأحبار",
      targetCategory: "it-peripherals",
    },
    {
      id: "slide-3",
      imageUrl: "/images/hero-backtoschool.jpg",
      badgeEn: "Retail & Wholesale B2B Supply",
      badgeAr: "البيع بالتقسيط وبالجملة للمؤسسات والمدارس",
      titleEn: "Complete Back-to-School & Bulk Institutional Packs",
      titleAr: "تجهيز شامل للعودة المدرسية وعروض خاصة للبيع بالجملة",
      subtitleEn:
        "Up to 30% wholesale discounts on school bags, scientific calculators, art markers, and A4 paper boxes.",
      subtitleAr:
        "خصومات تصل إلى 30% لطلبات الجملة على الحقائب المدرسية والآلات الحاسبة العلمية وأدوات الرسم وصناديق الورق.",
      ctaEn: "View Wholesale Offers",
      ctaAr: "عروض البيع بالجملة",
      targetCategory: "bags",
    },
  ],
  landscapeBanner: {
    imageUrl: "/images/landscape-banner.jpg",
    badgeEn: "THE COMPLETE STUDIO & OFFICE ECOSYSTEM",
    badgeAr: "منظومة متكاملة للدراسة والمكاتب الحديثة",
    titleEn: "Where Traditional Paper Craftsmanship Meets Digital Productivity",
    titleAr: "حيث تلتقي حرفية الورق الفاخر مع أحدث تقنيات المكتب الرقمي",
    subtitleEn:
      "Every item in our catalog is tested for durability, archival quality, and daily ergonomics — available individually or in wholesale cartons with instant WhatsApp ordering.",
    subtitleAr:
      "كل منتج في كتالوجنا مختبر بعناية لضمان المتانة والجودة العالية والراحة اليومية — متوفر بالقطعة أو بكميات الجملة مع طلب فوري ومباشر عبر واتساب.",
    ctaEn: "Open Full Master Catalog",
    ctaAr: "افتح الكتالوج الشامل",
  },
};

